// <auto-generated />
using System;
using LuckyContractMgr.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LuckyContractMgr.Migrations
{
    [DbContext(typeof(ContractContext))]
    [Migration("20210204123032_EFCore.Models.Seed")]
    partial class EFCoreModelsSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("LuckyContractMgr.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ContractExecutedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractTerminateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeOfWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminationTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractExecutedOn = new DateTime(2021, 2, 4, 13, 30, 31, 4, DateTimeKind.Local).AddTicks(6180),
                            ContractTerminateOn = new DateTime(2021, 2, 4, 13, 30, 31, 6, DateTimeKind.Local).AddTicks(5779),
                            PONumber = "PO00234",
                            PaymentTerms = "Time is the indefinite continued progress of existence and events that occur in an apparently irreversible succession from the past, through the present, into the future.",
                            RFQNumber = "RFQ000ZHRS",
                            ScopeOfWork = "Time is the indefinite continued progress of existence and events that occur in an apparently irreversible succession from the past, through the present, into the future.",
                            TerminationTerms = "Time is the indefinite continued progress of existence and events that occur in an apparently irreversible succession from the past, through the present, into the future.",
                            VendorCompanyName = "Ochukwu Ltd",
                            VendorContactPerson = "Lucky"
                        },
                        new
                        {
                            Id = 2,
                            ContractExecutedOn = new DateTime(2021, 2, 4, 13, 30, 31, 6, DateTimeKind.Local).AddTicks(7096),
                            ContractTerminateOn = new DateTime(2021, 2, 4, 13, 30, 31, 6, DateTimeKind.Local).AddTicks(7107),
                            PONumber = "PO00834",
                            PaymentTerms = "Time is the indefinite continued progress of existence and events that occur in an apparently irreversible succession from the past, through the present, into the future.",
                            RFQNumber = "RFQ00KHGS",
                            ScopeOfWork = "Time is the indefinite continued progress of existence and events that occur in an apparently irreversible succession from the past, through the present, into the future.",
                            TerminationTerms = "Time is the indefinite continued progress of existence and events that occur in an apparently irreversible succession from the past, through the present, into the future.",
                            VendorCompanyName = "KK LImited",
                            VendorContactPerson = "Lucky"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
